#!/bin/bash

# lua-npge, Nucleotide PanGenome explorer (Lua module)
# Copyright (C) 2014-2015 Boris Nagaev
# See the LICENSE file for terms of use.

# Usage:
# $ . /path/to/SETPATH
# $ lua
# $ npge = require('npge')

top_dir="$(readlink -f "$(dirname "$BASH_SOURCE")")"
new_path="$top_dir/src/?/init.lua"
new_path="$new_path;$top_dir/src/?.lua"
if [ -z "$LUA_PATH" ]; then
    export LUA_PATH="$new_path;`lua -e 'print(package.path)'`"
else
    export LUA_PATH="$new_path;$LUA_PATH"
fi

