local model = require 'npge.model'
local Row = model.Row

describe("model.row", function()
    it("uses row A-T-G-C", function()
        local r = Row("A-T-G-C")
        assert.are.equal(r:length(), 7)
        assert.are.equal(r:fragment_length(), 4)
        -- block2fragment
        assert.are.equal(r:block2fragment(0), 0)
        assert.are.equal(r:block2fragment(1), -1)
        assert.are.equal(r:block2fragment(2), 1)
        assert.are.equal(r:block2fragment(3), -1)
        assert.are.equal(r:block2fragment(4), 2)
        assert.are.equal(r:block2fragment(5), -1)
        assert.are.equal(r:block2fragment(6), 3)
        assert.has_error(function()
            r:block2fragment(-1)
        end)
        assert.has_error(function()
            r:block2fragment(-100)
        end)
        assert.has_error(function()
            r:block2fragment(7)
        end)
        assert.has_error(function()
            r:block2fragment(100)
        end)
        -- fragment2block
        assert.are.equal(r:fragment2block(0), 0)
        assert.are.equal(r:fragment2block(1), 2)
        assert.are.equal(r:fragment2block(2), 4)
        assert.are.equal(r:fragment2block(3), 6)
        assert.has_error(function()
            r:fragment2block(-1)
        end)
        assert.has_error(function()
            r:fragment2block(-100)
        end)
        assert.has_error(function()
            r:fragment2block(4)
        end)
        assert.has_error(function()
            r:fragment2block(100)
        end)
    end)
end)

