luarocks install busted
luarocks install luacov
luarocks install luacov-coveralls
luarocks install lua-llthreads2
luarocks install lcurses
luarocks install lua-rote
luarocks install alnbox
luarocks install tree
luarocks install luacheck
