luarocks install busted --local
luarocks install luacov --local
luarocks install luacov-coveralls --local
luarocks install lua-llthreads2 --local
luarocks install lcurses --local
luarocks install lua-rote --local
luarocks install alnbox --local
luarocks install tree --local
luarocks install luacheck --local
