return {
    split = require 'npge.util.split',
    unpack = require 'npge.util.unpack',
    arrays_equal = require 'npge.util.arrays_equal',
    arrays_less = require 'npge.util.arrays_less',
    binary_search = require 'npge.util.binary_search',
    concat_arrays = require 'npge.util.concat_arrays',
    unique = require 'npge.util.unique',
    clone = require 'npge.util.clone',
    it_from_array = require 'npge.util.it_from_array',
    extract_value = require 'npge.util.extract_value',
    as_lines = require 'npge.util.as_lines',
    starts_with = require 'npge.util.starts_with',
    ends_with = require 'npge.util.ends_with',
    trim = require 'npge.util.trim',
    write_it = require 'npge.util.write_it',
}
